baseURL = "https://www.jonaspasserini.com/"
languageCode = "en-us"
title = "Jonas Passerini"
theme = "hugo-paper"
publishDir = "docs"
canonifyurls = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true